// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action_ActionType int32

const (
	Action_UNKNOWN  Action_ActionType = 0
	Action_PLAY     Action_ActionType = 1
	Action_PAUSE    Action_ActionType = 2
	Action_NEXT     Action_ActionType = 3
	Action_PREVIOUS Action_ActionType = 4
	Action_SHUFFLE  Action_ActionType = 5
)

var Action_ActionType_name = map[int32]string{
	0: "UNKNOWN",
	1: "PLAY",
	2: "PAUSE",
	3: "NEXT",
	4: "PREVIOUS",
	5: "SHUFFLE",
}

var Action_ActionType_value = map[string]int32{
	"UNKNOWN":  0,
	"PLAY":     1,
	"PAUSE":    2,
	"NEXT":     3,
	"PREVIOUS": 4,
	"SHUFFLE":  5,
}

func (x Action_ActionType) String() string {
	return proto.EnumName(Action_ActionType_name, int32(x))
}

func (Action_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{0, 0}
}

type Action struct {
	UserId               string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action               Action_ActionType `protobuf:"varint,2,opt,name=action,proto3,enum=main.Action_ActionType" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Action) GetAction() Action_ActionType {
	if m != nil {
		return m.Action
	}
	return Action_UNKNOWN
}

func init() {
	proto.RegisterEnum("main.Action_ActionType", Action_ActionType_name, Action_ActionType_value)
	proto.RegisterType((*Action)(nil), "main.Action")
}

func init() {
	proto.RegisterFile("action.proto", fileDescriptor_59885c909ad4dfd3)
}

var fileDescriptor_59885c909ad4dfd3 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x5a,
	0xce, 0xc8, 0xc5, 0xe6, 0x08, 0x16, 0x16, 0x12, 0xe7, 0x62, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0xf4, 0xb9,
	0xd8, 0x20, 0x3a, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xc4, 0xf5, 0x40, 0x5a, 0xf5, 0x20,
	0xda, 0xa0, 0x54, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x54, 0x99, 0x52, 0x30, 0x17, 0x17, 0x42, 0x54,
	0x88, 0x9b, 0x8b, 0x3d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f, 0x80, 0x41, 0x88, 0x83, 0x8b,
	0x25, 0xc0, 0xc7, 0x31, 0x52, 0x80, 0x51, 0x88, 0x93, 0x8b, 0x35, 0xc0, 0x31, 0x34, 0xd8, 0x55,
	0x80, 0x09, 0x24, 0xe8, 0xe7, 0x1a, 0x11, 0x22, 0xc0, 0x2c, 0xc4, 0xc3, 0xc5, 0x11, 0x10, 0xe4,
	0x1a, 0xe6, 0xe9, 0x1f, 0x1a, 0x2c, 0xc0, 0x02, 0xd2, 0x19, 0xec, 0x11, 0xea, 0xe6, 0xe6, 0xe3,
	0x2a, 0xc0, 0x9a, 0xc4, 0x06, 0x76, 0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x02, 0xdc,
	0xdd, 0xc6, 0x00, 0x00, 0x00,
}
