// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delete_user.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteUser struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUser) Reset()         { *m = DeleteUser{} }
func (m *DeleteUser) String() string { return proto.CompactTextString(m) }
func (*DeleteUser) ProtoMessage()    {}
func (*DeleteUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d79e47055e10a6f, []int{0}
}

func (m *DeleteUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUser.Unmarshal(m, b)
}
func (m *DeleteUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUser.Marshal(b, m, deterministic)
}
func (m *DeleteUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUser.Merge(m, src)
}
func (m *DeleteUser) XXX_Size() int {
	return xxx_messageInfo_DeleteUser.Size(m)
}
func (m *DeleteUser) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUser.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUser proto.InternalMessageInfo

func (m *DeleteUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d79e47055e10a6f, []int{1}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteUserResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DeleteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteUser)(nil), "message.DeleteUser")
	proto.RegisterType((*DeleteUserResponse)(nil), "message.DeleteUserResponse")
}

func init() {
	proto.RegisterFile("delete_user.proto", fileDescriptor_8d79e47055e10a6f)
}

var fileDescriptor_8d79e47055e10a6f = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x8d, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52, 0xe5, 0xe2, 0x72, 0x01, 0xcb, 0x86, 0x16, 0xa7,
	0x16, 0x09, 0x89, 0x73, 0xb1, 0x83, 0x14, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x4a, 0xc1, 0x5c, 0x42, 0x08, 0x65, 0x41, 0xa9, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x38, 0x95, 0x0b, 0xf1, 0x71, 0x31, 0xe5, 0x67, 0x4b, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x04, 0x31, 0xe5, 0x67, 0x0b, 0x89, 0x70, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49,
	0x30, 0x83, 0x95, 0x41, 0x38, 0x49, 0x6c, 0x60, 0xb7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x82, 0x76, 0x36, 0xa0, 0x00, 0x00, 0x00,
}
