// Code generated by protoc-gen-go. DO NOT EDIT.
// source: join_room.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinRoom struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_323d208514f79492, []int{0}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinRoom) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type JoinRoomResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room                 *RefRoom `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_323d208514f79492, []int{1}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinRoomResponse) GetRoom() *RefRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *JoinRoomResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *JoinRoomResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*JoinRoom)(nil), "message.JoinRoom")
	proto.RegisterType((*JoinRoomResponse)(nil), "message.JoinRoomResponse")
}

func init() {
	proto.RegisterFile("join_room.proto", fileDescriptor_323d208514f79492)
}

var fileDescriptor_323d208514f79492 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0xc1, 0xca, 0xc2, 0x30,
	0x10, 0x84, 0x69, 0xfe, 0xfe, 0x6d, 0x5d, 0xa1, 0x96, 0x20, 0x18, 0x3c, 0x95, 0xe2, 0xa1, 0xa7,
	0x1c, 0xec, 0x53, 0xe8, 0x31, 0x2f, 0x50, 0x94, 0x6c, 0x25, 0x96, 0x76, 0xcb, 0x46, 0xf1, 0xf5,
	0xa5, 0x51, 0xf1, 0xe4, 0x71, 0x66, 0xf8, 0x66, 0x06, 0x56, 0x57, 0x72, 0x63, 0xcb, 0x44, 0x83,
	0x9e, 0x98, 0x6e, 0x24, 0xd3, 0x01, 0xbd, 0x3f, 0x5d, 0x70, 0x9b, 0x33, 0x76, 0xfa, 0x1b, 0x54,
	0x0d, 0x64, 0x47, 0x72, 0xa3, 0x21, 0x1a, 0xe4, 0x06, 0xd2, 0xbb, 0x47, 0x6e, 0x9d, 0x55, 0x51,
	0x19, 0xd5, 0x0b, 0x93, 0xcc, 0xf2, 0x60, 0x65, 0x0e, 0xc2, 0x59, 0x25, 0x82, 0x27, 0x9c, 0xad,
	0x1e, 0x50, 0x7c, 0x20, 0x83, 0x7e, 0xa2, 0xd1, 0xe3, 0x6f, 0x78, 0x07, 0xf1, 0xbc, 0x17, 0xf0,
	0xe5, 0xbe, 0xd0, 0xef, 0x27, 0xda, 0x60, 0x17, 0x0a, 0x42, 0x3a, 0x4f, 0x50, 0xaf, 0xfe, 0xca,
	0xa8, 0xce, 0x8c, 0xa0, 0x5e, 0xae, 0xe1, 0x1f, 0x99, 0x89, 0x55, 0x1c, 0xca, 0x5e, 0xe2, 0x9c,
	0x84, 0xd3, 0xcd, 0x33, 0x00, 0x00, 0xff, 0xff, 0x67, 0x0f, 0x1b, 0xb8, 0xe0, 0x00, 0x00, 0x00,
}
