// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leave_room.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LeaveRoom struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom) Reset()         { *m = LeaveRoom{} }
func (m *LeaveRoom) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom) ProtoMessage()    {}
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0e6dbee830f51f, []int{0}
}

func (m *LeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom.Unmarshal(m, b)
}
func (m *LeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom.Marshal(b, m, deterministic)
}
func (m *LeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom.Merge(m, src)
}
func (m *LeaveRoom) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom.Size(m)
}
func (m *LeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom proto.InternalMessageInfo

func (m *LeaveRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *LeaveRoom) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LeaveRoomResponse struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomResponse) Reset()         { *m = LeaveRoomResponse{} }
func (m *LeaveRoomResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResponse) ProtoMessage()    {}
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0e6dbee830f51f, []int{1}
}

func (m *LeaveRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResponse.Unmarshal(m, b)
}
func (m *LeaveRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResponse.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResponse.Merge(m, src)
}
func (m *LeaveRoomResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResponse.Size(m)
}
func (m *LeaveRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResponse proto.InternalMessageInfo

func (m *LeaveRoomResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *LeaveRoomResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LeaveRoomResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *LeaveRoomResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*LeaveRoom)(nil), "message.LeaveRoom")
	proto.RegisterType((*LeaveRoomResponse)(nil), "message.LeaveRoomResponse")
}

func init() {
	proto.RegisterFile("leave_room.proto", fileDescriptor_ed0e6dbee830f51f)
}

var fileDescriptor_ed0e6dbee830f51f = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x49, 0x4d, 0x2c,
	0x4b, 0x8d, 0x2f, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xb2, 0xe5, 0xe2, 0xf4, 0x01, 0x49, 0x06, 0xe5, 0xe7, 0xe7,
	0x0a, 0x89, 0x73, 0xb1, 0x83, 0xd4, 0xc4, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x20, 0x89, 0xd2, 0xe2, 0xd4, 0x22, 0x90, 0x04, 0x13, 0x44, 0x02,
	0xc4, 0xf5, 0x4c, 0x51, 0xca, 0xe6, 0x12, 0x84, 0x6b, 0x0f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x25, 0xdd, 0x18, 0x21, 0x3e, 0x2e, 0xa6, 0xfc, 0x6c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x8e,
	0x20, 0xa6, 0xfc, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0x09, 0x16, 0xb0,
	0x32, 0x08, 0x27, 0x89, 0x0d, 0xec, 0x76, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x06,
	0x49, 0x91, 0xcf, 0x00, 0x00, 0x00,
}
