// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listen.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListenResponse_ActionType int32

const (
	ListenResponse_STATE_CHANGE ListenResponse_ActionType = 0
)

var ListenResponse_ActionType_name = map[int32]string{
	0: "STATE_CHANGE",
}

var ListenResponse_ActionType_value = map[string]int32{
	"STATE_CHANGE": 0,
}

func (x ListenResponse_ActionType) String() string {
	return proto.EnumName(ListenResponse_ActionType_name, int32(x))
}

func (ListenResponse_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f05da38a4a3e5177, []int{1, 0}
}

type Listen struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listen) Reset()         { *m = Listen{} }
func (m *Listen) String() string { return proto.CompactTextString(m) }
func (*Listen) ProtoMessage()    {}
func (*Listen) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05da38a4a3e5177, []int{0}
}

func (m *Listen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listen.Unmarshal(m, b)
}
func (m *Listen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listen.Marshal(b, m, deterministic)
}
func (m *Listen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listen.Merge(m, src)
}
func (m *Listen) XXX_Size() int {
	return xxx_messageInfo_Listen.Size(m)
}
func (m *Listen) XXX_DiscardUnknown() {
	xxx_messageInfo_Listen.DiscardUnknown(m)
}

var xxx_messageInfo_Listen proto.InternalMessageInfo

func (m *Listen) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListenResponse struct {
	UserId               string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType           ListenResponse_ActionType `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=message.ListenResponse_ActionType" json:"action_type,omitempty"`
	Meta                 []byte                    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Ok                   bool                      `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string                    `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListenResponse) Reset()         { *m = ListenResponse{} }
func (m *ListenResponse) String() string { return proto.CompactTextString(m) }
func (*ListenResponse) ProtoMessage()    {}
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05da38a4a3e5177, []int{1}
}

func (m *ListenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenResponse.Unmarshal(m, b)
}
func (m *ListenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenResponse.Marshal(b, m, deterministic)
}
func (m *ListenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenResponse.Merge(m, src)
}
func (m *ListenResponse) XXX_Size() int {
	return xxx_messageInfo_ListenResponse.Size(m)
}
func (m *ListenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenResponse proto.InternalMessageInfo

func (m *ListenResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListenResponse) GetActionType() ListenResponse_ActionType {
	if m != nil {
		return m.ActionType
	}
	return ListenResponse_STATE_CHANGE
}

func (m *ListenResponse) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ListenResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ListenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.ListenResponse_ActionType", ListenResponse_ActionType_name, ListenResponse_ActionType_value)
	proto.RegisterType((*Listen)(nil), "message.Listen")
	proto.RegisterType((*ListenResponse)(nil), "message.ListenResponse")
}

func init() {
	proto.RegisterFile("listen.proto", fileDescriptor_f05da38a4a3e5177)
}

var fileDescriptor_f05da38a4a3e5177 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xc9, 0x2c, 0x2e,
	0x49, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x55, 0x52, 0xe4, 0x62, 0xf3, 0x01, 0x4b, 0x08, 0x89, 0x73, 0xb1, 0x97, 0x16, 0xa7, 0x16,
	0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x4a,
	0x27, 0x18, 0xb9, 0xf8, 0x20, 0x6a, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x71, 0xaa,
	0x15, 0x72, 0xe6, 0xe2, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x8b, 0x2f, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x52, 0x60, 0xd4, 0xe0, 0x33, 0x52, 0xd2, 0x83, 0xda, 0xa6, 0x87, 0x6a, 0x8c, 0x9e, 0x23,
	0x58, 0x69, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x57, 0x22, 0x9c, 0x2d, 0x24, 0xc4, 0xc5, 0x92, 0x9b,
	0x5a, 0x92, 0x28, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x0b, 0xf1, 0x71, 0x31, 0xe5,
	0x67, 0x4b, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x04, 0x31, 0xe5, 0x67, 0x0b, 0x89, 0x70, 0xb1, 0xa6,
	0x16, 0x15, 0xe5, 0x17, 0x49, 0xb0, 0x82, 0xed, 0x87, 0x70, 0x94, 0xe4, 0xb8, 0xb8, 0x10, 0x66,
	0x0a, 0x09, 0x70, 0xf1, 0x04, 0x87, 0x38, 0x86, 0xb8, 0xc6, 0x3b, 0x7b, 0x38, 0xfa, 0xb9, 0xbb,
	0x0a, 0x30, 0x24, 0xb1, 0x81, 0x7d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x86, 0xbe,
	0x74, 0x0d, 0x01, 0x00, 0x00,
}
