// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query_rooms.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRooms struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRooms) Reset()         { *m = QueryRooms{} }
func (m *QueryRooms) String() string { return proto.CompactTextString(m) }
func (*QueryRooms) ProtoMessage()    {}
func (*QueryRooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ccf6ec1fd53306, []int{0}
}

func (m *QueryRooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRooms.Unmarshal(m, b)
}
func (m *QueryRooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRooms.Marshal(b, m, deterministic)
}
func (m *QueryRooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRooms.Merge(m, src)
}
func (m *QueryRooms) XXX_Size() int {
	return xxx_messageInfo_QueryRooms.Size(m)
}
func (m *QueryRooms) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRooms.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRooms proto.InternalMessageInfo

func (m *QueryRooms) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryRoomsResponse struct {
	Room                 []*RefRoom `protobuf:"bytes,1,rep,name=room,proto3" json:"room,omitempty"`
	Ok                   bool       `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryRoomsResponse) Reset()         { *m = QueryRoomsResponse{} }
func (m *QueryRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRoomsResponse) ProtoMessage()    {}
func (*QueryRoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ccf6ec1fd53306, []int{1}
}

func (m *QueryRoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomsResponse.Unmarshal(m, b)
}
func (m *QueryRoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomsResponse.Marshal(b, m, deterministic)
}
func (m *QueryRoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomsResponse.Merge(m, src)
}
func (m *QueryRoomsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryRoomsResponse.Size(m)
}
func (m *QueryRoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomsResponse proto.InternalMessageInfo

func (m *QueryRoomsResponse) GetRoom() []*RefRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *QueryRoomsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *QueryRoomsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryRooms)(nil), "message.QueryRooms")
	proto.RegisterType((*QueryRoomsResponse)(nil), "message.QueryRoomsResponse")
}

func init() {
	proto.RegisterFile("query_rooms.proto", fileDescriptor_e4ccf6ec1fd53306)
}

var fileDescriptor_e4ccf6ec1fd53306 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xb1, 0xca, 0xc2, 0x40,
	0x0c, 0x80, 0xb9, 0xb6, 0xff, 0xaf, 0x46, 0x28, 0x1a, 0x1c, 0x0e, 0xa7, 0xa3, 0x38, 0x74, 0xba,
	0x41, 0x9f, 0xc4, 0xbc, 0x80, 0x56, 0x48, 0x1d, 0xca, 0x35, 0x35, 0xa7, 0x83, 0x6f, 0x2f, 0x77,
	0x15, 0xdc, 0x12, 0xbe, 0x8f, 0x2f, 0x81, 0xed, 0xe3, 0xc5, 0xfa, 0xbe, 0xa8, 0x48, 0x88, 0x7e,
	0x52, 0x79, 0x0a, 0x2e, 0x02, 0xc7, 0xd8, 0xdd, 0x79, 0x5f, 0x2b, 0xf7, 0x3e, 0x91, 0x19, 0x34,
	0x0e, 0xe0, 0x9c, 0x6c, 0x4a, 0x32, 0x22, 0x54, 0x63, 0x17, 0xd8, 0x1a, 0x67, 0xda, 0x15, 0xe5,
	0xb9, 0xb9, 0x02, 0xfe, 0x0c, 0xe2, 0x38, 0xc9, 0x18, 0x19, 0x0f, 0x50, 0xa5, 0x8a, 0x35, 0xae,
	0x6c, 0xd7, 0xc7, 0x8d, 0xff, 0xf6, 0x3d, 0x71, 0x9f, 0x44, 0xca, 0x14, 0x6b, 0x28, 0x64, 0xb0,
	0x85, 0x33, 0xed, 0x92, 0x0a, 0x19, 0x70, 0x07, 0x7f, 0xac, 0x2a, 0x6a, 0xcb, 0x7c, 0x60, 0x5e,
	0x6e, 0xff, 0xf9, 0x95, 0xd3, 0x27, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xbe, 0x3d, 0x49, 0xb8, 0x00,
	0x00, 0x00,
}
