// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ref.user_save.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefUserSave struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Client               []byte   `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Playlist             []byte   `protobuf:"bytes,4,opt,name=playlist,proto3" json:"playlist,omitempty"`
	PlaylistOwner        bool     `protobuf:"varint,5,opt,name=playlist_owner,json=playlistOwner,proto3" json:"playlist_owner,omitempty"`
	ClientId             string   `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Room                 string   `protobuf:"bytes,7,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefUserSave) Reset()         { *m = RefUserSave{} }
func (m *RefUserSave) String() string { return proto.CompactTextString(m) }
func (*RefUserSave) ProtoMessage()    {}
func (*RefUserSave) Descriptor() ([]byte, []int) {
	return fileDescriptor_364e98cc485e701d, []int{0}
}

func (m *RefUserSave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefUserSave.Unmarshal(m, b)
}
func (m *RefUserSave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefUserSave.Marshal(b, m, deterministic)
}
func (m *RefUserSave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefUserSave.Merge(m, src)
}
func (m *RefUserSave) XXX_Size() int {
	return xxx_messageInfo_RefUserSave.Size(m)
}
func (m *RefUserSave) XXX_DiscardUnknown() {
	xxx_messageInfo_RefUserSave.DiscardUnknown(m)
}

var xxx_messageInfo_RefUserSave proto.InternalMessageInfo

func (m *RefUserSave) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefUserSave) GetClient() []byte {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *RefUserSave) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *RefUserSave) GetPlaylist() []byte {
	if m != nil {
		return m.Playlist
	}
	return nil
}

func (m *RefUserSave) GetPlaylistOwner() bool {
	if m != nil {
		return m.PlaylistOwner
	}
	return false
}

func (m *RefUserSave) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RefUserSave) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func init() {
	proto.RegisterType((*RefUserSave)(nil), "message.RefUserSave")
}

func init() {
	proto.RegisterFile("ref.user_save.proto", fileDescriptor_364e98cc485e701d)
}

var fileDescriptor_364e98cc485e701d = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x6a, 0x84, 0x30,
	0x14, 0x85, 0x89, 0xb5, 0xfe, 0xdc, 0xb6, 0x2e, 0x6e, 0xa1, 0x84, 0x76, 0x23, 0x85, 0x82, 0x2b,
	0x37, 0x7d, 0x8a, 0xae, 0x0a, 0x29, 0x5d, 0x4b, 0xc6, 0x5c, 0x87, 0x80, 0x1a, 0x49, 0x32, 0x0e,
	0xf3, 0x78, 0xf3, 0x66, 0x83, 0x51, 0x67, 0x77, 0xbe, 0x0f, 0x0e, 0xf7, 0x1e, 0x78, 0xb5, 0xd4,
	0xd5, 0x27, 0x47, 0xb6, 0x71, 0x72, 0xa6, 0x7a, 0xb2, 0xc6, 0x1b, 0x4c, 0x07, 0x72, 0x4e, 0x1e,
	0xe9, 0xf3, 0xca, 0xe0, 0x49, 0x50, 0xf7, 0xef, 0xc8, 0xfe, 0xc9, 0x99, 0xb0, 0x80, 0x48, 0x2b,
	0xce, 0x4a, 0x56, 0xe5, 0x22, 0xd2, 0x0a, 0xdf, 0x20, 0x69, 0x7b, 0x4d, 0xa3, 0xe7, 0x51, 0xc9,
	0xaa, 0x67, 0xb1, 0xd1, 0xe2, 0x65, 0xeb, 0xf5, 0x4c, 0xfc, 0xa1, 0x64, 0x55, 0x26, 0x36, 0xc2,
	0x77, 0xc8, 0xa6, 0x5e, 0x5e, 0x7a, 0xed, 0x3c, 0x8f, 0x43, 0xe3, 0xce, 0xf8, 0x05, 0xc5, 0x9e,
	0x1b, 0x73, 0x1e, 0xc9, 0xf2, 0xc7, 0xd0, 0x7d, 0xd9, 0xed, 0xef, 0x22, 0xf1, 0x03, 0xf2, 0xf5,
	0x48, 0xa3, 0x15, 0x4f, 0xc2, 0x27, 0xd9, 0x2a, 0x7e, 0x14, 0x22, 0xc4, 0xd6, 0x98, 0x81, 0xa7,
	0xc1, 0x87, 0x7c, 0x48, 0xc2, 0xa6, 0xef, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x2d, 0xe9,
	0xf8, 0xea, 0x00, 0x00, 0x00,
}
