// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ref.room.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefRoom struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefRoom) Reset()         { *m = RefRoom{} }
func (m *RefRoom) String() string { return proto.CompactTextString(m) }
func (*RefRoom) ProtoMessage()    {}
func (*RefRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_7106929103f8844f, []int{0}
}

func (m *RefRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefRoom.Unmarshal(m, b)
}
func (m *RefRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefRoom.Marshal(b, m, deterministic)
}
func (m *RefRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefRoom.Merge(m, src)
}
func (m *RefRoom) XXX_Size() int {
	return xxx_messageInfo_RefRoom.Size(m)
}
func (m *RefRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_RefRoom.DiscardUnknown(m)
}

var xxx_messageInfo_RefRoom proto.InternalMessageInfo

func (m *RefRoom) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefRoom) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*RefRoom)(nil), "message.RefRoom")
}

func init() {
	proto.RegisterFile("ref.room.proto", fileDescriptor_7106929103f8844f)
}

var fileDescriptor_7106929103f8844f = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xd3,
	0x2b, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x55, 0xd2, 0xe5, 0x62, 0x0f, 0x4a, 0x4d, 0x0b, 0xca, 0xcf, 0xcf, 0x15, 0xe2,
	0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12,
	0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x93,
	0xd8, 0xc0, 0xda, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xbc, 0xdd, 0xcf, 0x50, 0x00,
	0x00, 0x00,
}
