// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ref.track.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefTrack struct {
	Artists              []*RefArtist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Duration             int64        `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Id                   string       `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  string       `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefTrack) Reset()         { *m = RefTrack{} }
func (m *RefTrack) String() string { return proto.CompactTextString(m) }
func (*RefTrack) ProtoMessage()    {}
func (*RefTrack) Descriptor() ([]byte, []int) {
	return fileDescriptor_04496c1828ce7006, []int{0}
}

func (m *RefTrack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefTrack.Unmarshal(m, b)
}
func (m *RefTrack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefTrack.Marshal(b, m, deterministic)
}
func (m *RefTrack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefTrack.Merge(m, src)
}
func (m *RefTrack) XXX_Size() int {
	return xxx_messageInfo_RefTrack.Size(m)
}
func (m *RefTrack) XXX_DiscardUnknown() {
	xxx_messageInfo_RefTrack.DiscardUnknown(m)
}

var xxx_messageInfo_RefTrack proto.InternalMessageInfo

func (m *RefTrack) GetArtists() []*RefArtist {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *RefTrack) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *RefTrack) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefTrack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RefTrack) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*RefTrack)(nil), "message.RefTrack")
}

func init() {
	proto.RegisterFile("ref.track.proto", fileDescriptor_04496c1828ce7006)
}

var fileDescriptor_04496c1828ce7006 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x41, 0x0e, 0x82, 0x30,
	0x10, 0x45, 0x53, 0x8a, 0x82, 0x63, 0xa2, 0x64, 0x56, 0x0d, 0x2b, 0xe2, 0x8a, 0x85, 0xe9, 0x42,
	0x4f, 0xe0, 0x15, 0x1a, 0x2f, 0x50, 0x65, 0x30, 0x8d, 0x01, 0xcc, 0xb4, 0x5c, 0xc2, 0x53, 0x9b,
	0x16, 0x75, 0xf7, 0xe7, 0xbf, 0x37, 0xc9, 0x87, 0x3d, 0x53, 0xaf, 0x03, 0xdb, 0xfb, 0x53, 0xbf,
	0x78, 0x0a, 0x13, 0x16, 0x03, 0x79, 0x6f, 0x1f, 0x54, 0x57, 0x91, 0x58, 0x0e, 0xce, 0x87, 0x05,
	0x1d, 0xde, 0x02, 0x4a, 0x43, 0xfd, 0x35, 0xda, 0x78, 0x84, 0x62, 0x81, 0x5e, 0x89, 0x46, 0xb6,
	0xdb, 0x13, 0xea, 0xef, 0xa7, 0x36, 0xd4, 0x5f, 0x12, 0x32, 0x3f, 0x05, 0x6b, 0x28, 0xbb, 0x99,
	0x6d, 0x70, 0xd3, 0xa8, 0xb2, 0x46, 0xb4, 0xd2, 0xfc, 0x6f, 0xdc, 0x41, 0xe6, 0x3a, 0x25, 0x1b,
	0xd1, 0x6e, 0x4c, 0xe6, 0x3a, 0x44, 0xc8, 0x47, 0x3b, 0x90, 0xca, 0x53, 0x93, 0x32, 0x56, 0x20,
	0x67, 0x76, 0x6a, 0x95, 0xaa, 0x18, 0x6f, 0xeb, 0xb4, 0xe9, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0x63, 0x39, 0x0d, 0xc1, 0x00, 0x00, 0x00,
}
