// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room_exists.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomExists struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomExists) Reset()         { *m = RoomExists{} }
func (m *RoomExists) String() string { return proto.CompactTextString(m) }
func (*RoomExists) ProtoMessage()    {}
func (*RoomExists) Descriptor() ([]byte, []int) {
	return fileDescriptor_924daaae9c78b197, []int{0}
}

func (m *RoomExists) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomExists.Unmarshal(m, b)
}
func (m *RoomExists) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomExists.Marshal(b, m, deterministic)
}
func (m *RoomExists) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomExists.Merge(m, src)
}
func (m *RoomExists) XXX_Size() int {
	return xxx_messageInfo_RoomExists.Size(m)
}
func (m *RoomExists) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomExists.DiscardUnknown(m)
}

var xxx_messageInfo_RoomExists proto.InternalMessageInfo

func (m *RoomExists) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomExistsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exists               bool     `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomExistsResponse) Reset()         { *m = RoomExistsResponse{} }
func (m *RoomExistsResponse) String() string { return proto.CompactTextString(m) }
func (*RoomExistsResponse) ProtoMessage()    {}
func (*RoomExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_924daaae9c78b197, []int{1}
}

func (m *RoomExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomExistsResponse.Unmarshal(m, b)
}
func (m *RoomExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomExistsResponse.Marshal(b, m, deterministic)
}
func (m *RoomExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomExistsResponse.Merge(m, src)
}
func (m *RoomExistsResponse) XXX_Size() int {
	return xxx_messageInfo_RoomExistsResponse.Size(m)
}
func (m *RoomExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomExistsResponse proto.InternalMessageInfo

func (m *RoomExistsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *RoomExistsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RoomExistsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomExists)(nil), "message.RoomExists")
	proto.RegisterType((*RoomExistsResponse)(nil), "message.RoomExistsResponse")
}

func init() {
	proto.RegisterFile("room_exists.proto", fileDescriptor_924daaae9c78b197)
}

var fileDescriptor_924daaae9c78b197 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xca, 0xcf, 0xcf,
	0x8d, 0x4f, 0xad, 0xc8, 0x2c, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x92, 0xe1, 0xe2, 0x0a, 0xca, 0xcf, 0xcf, 0x75, 0x05,
	0x4b, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65,
	0xa6, 0x28, 0x25, 0x71, 0x09, 0x21, 0x64, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xd1,
	0x55, 0x09, 0x89, 0x71, 0xb1, 0x41, 0x0c, 0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0xf2,
	0x40, 0xea, 0xf2, 0xb3, 0x25, 0x98, 0xc1, 0x62, 0x4c, 0xf9, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0x45, 0x45, 0xf9, 0x45, 0x12, 0x2c, 0x60, 0xad, 0x10, 0x4e, 0x12, 0x1b, 0xd8, 0x45, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd8, 0xdf, 0x97, 0xa6, 0x00, 0x00, 0x00,
}
