// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rooms.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rooms struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rooms) Reset()         { *m = Rooms{} }
func (m *Rooms) String() string { return proto.CompactTextString(m) }
func (*Rooms) ProtoMessage()    {}
func (*Rooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_98885a3990d96e2f, []int{0}
}

func (m *Rooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rooms.Unmarshal(m, b)
}
func (m *Rooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rooms.Marshal(b, m, deterministic)
}
func (m *Rooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rooms.Merge(m, src)
}
func (m *Rooms) XXX_Size() int {
	return xxx_messageInfo_Rooms.Size(m)
}
func (m *Rooms) XXX_DiscardUnknown() {
	xxx_messageInfo_Rooms.DiscardUnknown(m)
}

var xxx_messageInfo_Rooms proto.InternalMessageInfo

func (m *Rooms) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomsResponse struct {
	Room                 []*RefRoom `protobuf:"bytes,1,rep,name=room,proto3" json:"room,omitempty"`
	Ok                   bool       `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomsResponse) Reset()         { *m = RoomsResponse{} }
func (m *RoomsResponse) String() string { return proto.CompactTextString(m) }
func (*RoomsResponse) ProtoMessage()    {}
func (*RoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98885a3990d96e2f, []int{1}
}

func (m *RoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsResponse.Unmarshal(m, b)
}
func (m *RoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsResponse.Marshal(b, m, deterministic)
}
func (m *RoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsResponse.Merge(m, src)
}
func (m *RoomsResponse) XXX_Size() int {
	return xxx_messageInfo_RoomsResponse.Size(m)
}
func (m *RoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsResponse proto.InternalMessageInfo

func (m *RoomsResponse) GetRoom() []*RefRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *RoomsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RoomsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Rooms)(nil), "message.Rooms")
	proto.RegisterType((*RoomsResponse)(nil), "message.RoomsResponse")
}

func init() {
	proto.RegisterFile("rooms.proto", fileDescriptor_98885a3990d96e2f)
}

var fileDescriptor_98885a3990d96e2f = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0xbb, 0x0a, 0xc3, 0x30,
	0x0c, 0x05, 0x50, 0x9c, 0x47, 0x1f, 0x0a, 0x0d, 0x45, 0x74, 0x30, 0xed, 0x62, 0x42, 0x07, 0x4f,
	0x1e, 0xda, 0x3f, 0xd1, 0xda, 0x29, 0x05, 0xa5, 0x43, 0x70, 0x14, 0xe4, 0xfe, 0x3f, 0xc5, 0x4e,
	0x37, 0x89, 0x73, 0x75, 0x11, 0x74, 0x2a, 0x12, 0x53, 0x58, 0x55, 0xbe, 0x82, 0xfb, 0xc8, 0x29,
	0x8d, 0x1f, 0xbe, 0xf6, 0xca, 0x53, 0xc8, 0xb2, 0xc1, 0x70, 0x83, 0x96, 0x72, 0x0e, 0x11, 0x9a,
	0x65, 0x8c, 0x6c, 0x8d, 0x33, 0xfe, 0x48, 0x65, 0x1e, 0x5e, 0x70, 0x2a, 0x48, 0x9c, 0x56, 0x59,
	0x12, 0xe3, 0x1d, 0x9a, 0x7c, 0x6b, 0x8d, 0xab, 0x7d, 0xf7, 0x38, 0x87, 0x7f, 0x6b, 0x20, 0x9e,
	0x72, 0x90, 0x8a, 0x62, 0x0f, 0x95, 0xcc, 0xb6, 0x72, 0xc6, 0x1f, 0xa8, 0x92, 0x19, 0x2f, 0xd0,
	0xb2, 0xaa, 0xa8, 0xad, 0x4b, 0xf7, 0xb6, 0xbc, 0x77, 0xe5, 0x81, 0xe7, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0xc5, 0x6f, 0x5f, 0xa8, 0x00, 0x00, 0x00,
}
