// Code generated by protoc-gen-go. DO NOT EDIT.
// source: track.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Track struct {
	Artists              []*Artist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Duration             int64     `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Id                   string    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  string    `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b44cacdae97aca, []int{0}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetArtists() []*Artist {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *Track) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Track) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Track) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Track) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*Track)(nil), "message.Track")
}

func init() {
	proto.RegisterFile("track.proto", fileDescriptor_f4b44cacdae97aca)
}

var fileDescriptor_f4b44cacdae97aca = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0x4c,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0xe2, 0x49, 0x2c, 0x2a, 0xc9, 0x2c, 0x2e, 0x81, 0x08, 0x2b, 0xb5, 0x30, 0x72, 0xb1, 0x86,
	0x80, 0x94, 0x09, 0x69, 0x72, 0xb1, 0x43, 0x64, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d,
	0xf8, 0xf5, 0xa0, 0x5a, 0xf4, 0x1c, 0xc1, 0xe2, 0x41, 0x30, 0x79, 0x21, 0x29, 0x2e, 0x8e, 0x94,
	0xd2, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x38, 0x5f,
	0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x88, 0x29, 0x33, 0x45,
	0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x05, 0x2c, 0x02, 0x66, 0x0b, 0x09, 0x70,
	0x31, 0x97, 0x16, 0x65, 0x4a, 0xb0, 0x82, 0x85, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0x6b, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0xac, 0xa4, 0xf8, 0xb3, 0x00, 0x00, 0x00,
}
