// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_room.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRoom struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoom) Reset()         { *m = UserRoom{} }
func (m *UserRoom) String() string { return proto.CompactTextString(m) }
func (*UserRoom) ProtoMessage()    {}
func (*UserRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_8824073f0534de5e, []int{0}
}

func (m *UserRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoom.Unmarshal(m, b)
}
func (m *UserRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoom.Marshal(b, m, deterministic)
}
func (m *UserRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoom.Merge(m, src)
}
func (m *UserRoom) XXX_Size() int {
	return xxx_messageInfo_UserRoom.Size(m)
}
func (m *UserRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoom.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoom proto.InternalMessageInfo

func (m *UserRoom) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserRoomResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoomResponse) Reset()         { *m = UserRoomResponse{} }
func (m *UserRoomResponse) String() string { return proto.CompactTextString(m) }
func (*UserRoomResponse) ProtoMessage()    {}
func (*UserRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8824073f0534de5e, []int{1}
}

func (m *UserRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoomResponse.Unmarshal(m, b)
}
func (m *UserRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoomResponse.Marshal(b, m, deterministic)
}
func (m *UserRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoomResponse.Merge(m, src)
}
func (m *UserRoomResponse) XXX_Size() int {
	return xxx_messageInfo_UserRoomResponse.Size(m)
}
func (m *UserRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoomResponse proto.InternalMessageInfo

func (m *UserRoomResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRoomResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *UserRoomResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UserRoomResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRoom)(nil), "message.UserRoom")
	proto.RegisterType((*UserRoomResponse)(nil), "message.UserRoomResponse")
}

func init() {
	proto.RegisterFile("user_room.proto", fileDescriptor_8824073f0534de5e)
}

var fileDescriptor_8824073f0534de5e = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52, 0xe6, 0xe2, 0x08, 0x2d, 0x4e, 0x2d, 0x0a, 0xca, 0xcf, 0xcf,
	0x15, 0x12, 0xe7, 0x62, 0x07, 0xab, 0xcb, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62,
	0x03, 0x71, 0x3d, 0x53, 0x94, 0xb2, 0xb8, 0x04, 0x60, 0x8a, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x71, 0x2a, 0x06, 0x49, 0x80, 0x2c, 0x02, 0x49, 0x30, 0x41, 0x24, 0x40, 0x5c, 0xcf,
	0x14, 0x21, 0x3e, 0x2e, 0xa6, 0xfc, 0x6c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xa6, 0xfc,
	0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0x09, 0x16, 0xb0, 0x32, 0x08, 0x27,
	0x89, 0x0d, 0xec, 0x40, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0x0f, 0x2e, 0xc1, 0xb3,
	0x00, 0x00, 0x00,
}
