// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_leave_room.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLeaveRoom struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLeaveRoom) Reset()         { *m = UserLeaveRoom{} }
func (m *UserLeaveRoom) String() string { return proto.CompactTextString(m) }
func (*UserLeaveRoom) ProtoMessage()    {}
func (*UserLeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_556272dfc6b324b5, []int{0}
}

func (m *UserLeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLeaveRoom.Unmarshal(m, b)
}
func (m *UserLeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLeaveRoom.Marshal(b, m, deterministic)
}
func (m *UserLeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLeaveRoom.Merge(m, src)
}
func (m *UserLeaveRoom) XXX_Size() int {
	return xxx_messageInfo_UserLeaveRoom.Size(m)
}
func (m *UserLeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_UserLeaveRoom proto.InternalMessageInfo

func (m *UserLeaveRoom) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserLeaveRoomResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLeaveRoomResponse) Reset()         { *m = UserLeaveRoomResponse{} }
func (m *UserLeaveRoomResponse) String() string { return proto.CompactTextString(m) }
func (*UserLeaveRoomResponse) ProtoMessage()    {}
func (*UserLeaveRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_556272dfc6b324b5, []int{1}
}

func (m *UserLeaveRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLeaveRoomResponse.Unmarshal(m, b)
}
func (m *UserLeaveRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLeaveRoomResponse.Marshal(b, m, deterministic)
}
func (m *UserLeaveRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLeaveRoomResponse.Merge(m, src)
}
func (m *UserLeaveRoomResponse) XXX_Size() int {
	return xxx_messageInfo_UserLeaveRoomResponse.Size(m)
}
func (m *UserLeaveRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLeaveRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLeaveRoomResponse proto.InternalMessageInfo

func (m *UserLeaveRoomResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserLeaveRoomResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UserLeaveRoomResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLeaveRoom)(nil), "message.UserLeaveRoom")
	proto.RegisterType((*UserLeaveRoomResponse)(nil), "message.UserLeaveRoomResponse")
}

func init() {
	proto.RegisterFile("user_leave_room.proto", fileDescriptor_556272dfc6b324b5)
}

var fileDescriptor_556272dfc6b324b5 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0x49, 0x4d, 0x2c, 0x4b, 0x8d, 0x2f, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xd2, 0xe0, 0xe2, 0x0d, 0x2d,
	0x4e, 0x2d, 0xf2, 0x01, 0x29, 0x08, 0xca, 0xcf, 0xcf, 0x15, 0x12, 0xe7, 0x62, 0x07, 0x6b, 0xc9,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x94, 0xc2, 0xb8,
	0x44, 0x51, 0x54, 0x06, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xe2, 0xd4, 0x21, 0xc4, 0xc7,
	0xc5, 0x94, 0x9f, 0x2d, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x11, 0xc4, 0x94, 0x9f, 0x2d, 0x24, 0xc2,
	0xc5, 0x9a, 0x5a, 0x54, 0x94, 0x5f, 0x24, 0xc1, 0x0c, 0x56, 0x06, 0xe1, 0x24, 0xb1, 0x81, 0x5d,
	0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xc0, 0xb1, 0x09, 0xaa, 0x00, 0x00, 0x00,
}
